### ISSUE TITLE
Should Routes.js show up in the sidebar?

### ISSUE THREAD

**Issue by jtoar** [decoupled/studio#26]
This extension is great! I feel like I understand Redwood better just by using it.

Should `Routes.js` show up in the sidebar? It's one of the core Redwood files. E.g.:

![sidebar-with-routes](https://user-images.githubusercontent.com/32992335/80835393-84adbf80-8ba7-11ea-8d09-e60ff680a174.png)

I know you can navigate to it via a page, but just wanted to know what you thought about having it there explicitly.

**Comment by aldonline** [comment]
Hi Dominic!
Thanks for the great feedback. And I'm really happy you like this ;)
You're absolutely right that Routes.js deserves a spot. It is, in many ways, the center of the Redwood experience after all.
Added in 0.1.26
