### ISSUE TITLE
Add options to save and up the db 

### ISSUE THREAD

**Issue by jtoar** [decoupled/studio#28]
Similar to how there's page options on highlighting (i.e. open in a browser, open the react component, open the router def), could there be options to save/up the db on `schema.prisma` highlighting?

![sidebar-prisma](https://user-images.githubusercontent.com/32992335/80836530-ca6b8780-8ba9-11ea-81b7-5ad49cb84284.png)

**Comment by aldonline** [comment]
Hi Dominic.
Added something similar in 0.1.28
<img width="301" alt="Screen Shot 2020-05-06 at 6 19 19 PM" src="https://user-images.githubusercontent.com/154884/81244030-26794600-8fc6-11ea-873f-daaf4ca1b181.png">
