### ISSUE TITLE
Allow the user to "quick jump" to a location in the outline using cmd+shift+p"

### ISSUE THREAD

**Issue by peterp** [decoupled/studio#31]
Using `> rw routes` would open `routes.js|ts`, or `> redwood schema` would open `schema.prisma`

![image](https://user-images.githubusercontent.com/44849/81043000-ac579d00-8eb1-11ea-8831-551e3450eedd.png)

**Comment by aldonline** [comment]
Added on 0.1.28 :)
Note: The Redwood project outline does not navigate automatically (yet)

<img width="722" alt="Screen Shot 2020-05-06 at 6 16 51 PM" src="https://user-images.githubusercontent.com/154884/81243856-cc788080-8fc5-11ea-99f9-b937587ebf07.png">
